name: Lint and Build check

on:
  push:
    branches: 
      - master
  pull_request:
    branches: [master]
  
jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: SetUp Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.x
          cache: 'npm'
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Run linters
        run: npm run lint
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: SetUp Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.x
          cache: 'npm'
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Build
        run: npm run build